# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
sudo: false
cache: packages
cran: https://cran.rstudio.com/
warnings_are_errors: false
r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes --no-manual'

matrix:
  include:
  - r: bioc-release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: bioc-devel
