# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
cache: packages
r_check_args: '--as-cran'
bioc_required: true
bioc_use_devel: true
r_packages:
  - devtools
