# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes --no-manual'

bioc_check: true

matrix:
  include:
  - r: bioc-release
  - r: bioc-devel
